### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by smiffy6969** [Metric/Less-Compile#4]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:55:11)
Object.activate (/home/paul/.atom/packages/lesscompile/lib/lesscompile.coffee:38:9)
```

**Comment by Metric** [comment]
It is now fixed and updated for the latest version of Atom. Be sure to go into Atom preferences and update the package.

**Comment by smiffy6969** [comment]
Cheers mate.
