### ISSUE TITLE
Package.getActivationCommands is deprecated.

### ISSUE THREAD

**Issue by keeper32** [Metric/Less-Compile#5]
Use `activationCommands` instead of `activationEvents` in your package.json
Commands should be grouped by selector as follows:
```json
  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
```
```
Package.getActivationCommands (C:\Users\marcelo.nunes\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:790:9)
Package.hasActivationCommands (C:\Users\marcelo.nunes\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:715:20)
<unknown> (C:\Users\marcelo.nunes\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:169:24)
Package.measure (C:\Users\marcelo.nunes\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:147:15)
```

**Comment by smiffy6969** [comment]
Hi,

Is this package still being maintained? this is still an issue.

kind regards

Paul

**Comment by Metric** [comment]
I have already fixed it on the local build. I just haven't uploaded it yet
to apm / github.

**Comment by smiffy6969** [comment]
ahh ok, just seen this issue for quite some months now and wondered, thanks a lot.

**Comment by Metric** [comment]
Alright, there should be a package update now through atom that fixes this issue.
